name: hcr
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - blast
  - pandas #1.5.3
  - numpy #1.23.5
  - python
  - voila
  - pip
  - pip:
    - ipykernel
    - bio
    - ipyform
    - ipydatagrid